[package]
name = "webgl"
version = "0.1.0"
authors = ["Diggory Blake"]

[dependencies]
stdweb = { path = "../.." }
serde = "1.0.0"
serde_derive = "1.0.0"

[build-dependencies]
gl_generator = { path = "../../../gl-rs/gl_generator", features = ["webgl"] }
